version: "3.7"

secrets:
  cf_api_email:
    file: "./secrets/cf_api_email.secret"
  cf_api_key:
    file: "./secrets/cf_api_key.secret"
  db_password:
    file: "./secrets/db.secret"

services:
  traefik:
    image: "traefik:v2.0.1"
    container_name: "traefik"
    restart: always
    command:
#Set to DEBUG when problemsolving - reset to WARN when done
      - "--log.level=WARN" 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/dyn.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.seafilewebapp.address=:8000"
      - "--entrypoints.seafilewebdavserver.address=:8080"
      - "--entrypoints.seafilefileserver.address=:8082"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=admin@example.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
      - "8082:8082"      
    secrets:
      - "cf_api_email"
      - "cf_api_key"
    environment:
      - "CF_API_EMAIL_FILE=/run/secrets/cf_api_email"
      - "CF_API_KEY_FILE=/run/secrets/cf_api_key"
    volumes:
      - "./traefik/acme:/etc/acme"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dyn.yml:/etc/dyn.yml"
  memcached:
    image: memcached:1.5.19-alpine
    container_name: seafile-memcached
    restart: always
    entrypoint: memcached -m 128
  mariadb:
    image: mariadb:10.4.8
    container_name: mariadb
    restart: always
    command: --max_allowed_packet=128M
    volumes:
      - db:/var/lib/mysql
    secrets:
      - "db_password"
    environment:
      - "MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password"
  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    restart: always
    volumes:
      - data:/shared
#    secrets: #doesn't seem to implemented
#      - "db_password"
    environment:
      - "DB_HOST=mariadb"
      - "DB_ROOT_PASSWD=SECRETPASS"
      - "TIME_ZONE=Europe/Copenhagen"
      - "SEAFILE_ADMIN_EMAIL=mail@example.com"
      - "SEAFILE_ADMIN_PASSWORD=PASSWORD"
      - "SEAFILE_SERVER_HOSTNAME=sf.example.com"
      - "SEAFILE_SERVICE_URL=https://sf.example.com"
    depends_on:
      - mariadb
      - memcached
# Elasticsearch might be added later on...
      #- elasticsearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile.rule=Host(`sf.example.com`)"
      - "traefik.http.routers.seafile.entrypoints=websecure"
      - "traefik.http.routers.seafile.tls.certresolver=cloudflare"
      - "traefik.http.routers.seafile.middlewares=hardenizeheaders@file"
      - "traefik.http.routers.seafilewebapp.rule=Host(`sf.kennethandersen.com`)"
      - "traefik.http.routers.seafilewebapp.entrypoints=seafilewebapp"
      - "traefik.http.routers.seafilewebapp.tls.certresolver=cloudflare"
      - "traefik.http.routers.seafilewebdavserver.rule=Host(`sf.kennethandersen.com`) && PathPrefix(`/seafdav`)"
      - "traefik.http.routers.seafilewebdavserver.entrypoints=seafilewebdavserver"
      - "traefik.http.routers.seafilewebdavserver.tls.certresolver=cloudflare"
      - "traefik.http.routers.seafilefileserver.rule=Host(`sf.kennethandersen.com`) && PathPrefix(`/seafhttp`)"
      - "traefik.http.routers.seafilefileserver.entrypoints=seafilefileserver"
      - "traefik.http.routers.seafilefileserver.tls.certresolver=cloudflare"

volumes:
  db:
  data:
